language: python

python:
  - "3.7"

cache: pip

install: 
 - "pip install pytest"
 - "pip install pylint"

script:
 - "git clone https://github.com/AgPipeline/Organization-info.git"
 - mv test-files/*.py .
 - rm -r test-files/
 - "pylint --rcfile=Organization-info/pylint.rc *.py"
 - "python -m pytest -v"